### ISSUE TITLE
[Suggestion]: Allow geoip-connect-notice use the new UnrealIRCD 5.0.9 system

### ISSUE THREAD

**Issue by westor7** [pirc-pl/unrealircd-modules#10]
Hello,

I wonder if it is possible for `geoip-connect-notice` module to be able to use the new UnrealIRCD 5.0.9 system, that means instead of sending two notices to be able to merge that in the default that unrealircd using, i will provide some examples.

As suggested on https://github.com/unrealircd/unrealircd/commit/1baf5f9f7d265caa3a47bc2d582a37abf714cad8 there seems to be a way for coders to do that.

Examples (_IP's are random_):

Before:

`tester!4ddb0ff8@94FDCB46.48266416.2B90D540.IP is connecting from (Europe/LV) Latvia`
`*** Client connecting: tester (4ddb0ff8@77.219.15.248) [77.219.15.248] [account: testing] [secure: TLSv1.3-TLS_CHACHA20_POLY1305_SHA256] [class: clients]`

After:

`*** Client connecting: tester (4ddb0ff8@77.219.15.248) [77.219.15.248] [account: testing] [secure: TLSv1.3-TLS_CHACHA20_POLY1305_SHA256] [class: clients] [location: (Europe/LV) Latvia]`

- Thanks!

**Comment by k4bek4be** [comment]
I've already thought that out. There are two problems:
- Using the CONNECT_EXTINFO hook would require the module on every server, while the current solution is required to be only on a single one.
- Users of older IRCd version would like to be able to still use the module.

I think the solution is to create a new module, maybe geoip-connect-notice-new.

**Comment by westor7** [comment]
Oh i didn't knew about the CONNECT_EXTINFO thing, but for the 2nd one i think if you change the existence module to only work for 5.0.9+ then the 99% of the servers are going to update because this is something that almost everybody wants it, so i personally think its not necessary to create to modules about this.

**Comment by westor7** [comment]
It's already there on UnrealIRCD 6.x
