### ISSUE TITLE
problem between geoip ban and geoip-base

### ISSUE THREAD

**Issue by radmx** [pirc-pl/unrealircd-modules#11]
hi all, i've installed geoip ban (paid version) and it crashes between that module and geoip-base because when it loads (/rehash) on terminal pops out something like this:

Loading IRCd configuration..
[warning] /home/ircd/unrealircd/conf/deepconf/blacklist.conf:310: unknown item geoip::ipv4-blocks-file
[warning] /home/ircd/unrealircd/conf/deepconf/blacklist.conf:311: unknown item geoip::ipv6-blocks-file
[warning] /home/ircd/unrealircd/conf/deepconf/blacklist.conf:312: unknown item geoip::countries-file
[warning] geoip-base: no "geoip" config block found, using default file locations

on those lines:

geoip {
ipv4-blocks-file "GeoLite2-Country-Blocks-IPv4.csv";
ipv6-blocks-file "GeoLite2-Country-Blocks-IPv6.csv";
countries-file "GeoLite2-Country-Locations-en.csv";
};

and crashes ircd and dont load again until i comment out # the geoip-base and geoip-whois and his respective piece of conf...

before geoip ban, i have geoip-base, geoip-whois , geoip-connect-info properly configured and running and no problem, but now this...

any idea?
best regards

**Comment by k4bek4be** [comment]
I don't know what's a "geoip ban (paid version)", i've never made anything like that. It's likely a module from other author that makes `geoip-base` not read its configuration.
