### ISSUE TITLE
findchmodes doesn't work after upgrade to 5.2.1

### ISSUE THREAD

**Issue by Shillos** [pirc-pl/unrealircd-modules#17]
I got this message after the upgrade /home/ircd/unreal//conf/modules.extra.conf:13: loadmodule third/findchmodes: failed to load: Cannot open module file: No such file or directory I don't know what is missing although its loaded I'll try to re-install.

**Comment by k4bek4be** [comment]
Updated in 6fea94659dc6e22da0ff481e12192547eed7f10c
