### ISSUE TITLE
Ban a country in a channel

### ISSUE THREAD

**Issue by amoutai** [pirc-pl/unrealircd-modules#2]
Hi k4be,

With this module : https://forums.unrealircd.org/viewtopic.php?f=52&p=39016&sid=2c5498038af39b897f18c18cbbe71340#p39016

can you create a mode to ban a country in a channel? +Q "Country" example: /mode #channel +Q Maroc

Thanks :)

**Comment by TehPeGaSuS** [comment]
This can be something that can lead later to use that as a network banning module, kinda of what's used [here](https://www.unrealircd.org/docs/Configuration#Ban_user_block).  

Probably a way ti make them interact?

Cheers

**Comment by k4bek4be** [comment]
I'm waiting for geoip API to appear in unrealircd, to avoid loading my whois module (that is resource intensive) on every server. (I may create one myself if this is getting too long). This is also valid for the other request (https://github.com/pirc-pl/unrealircd-modules/issues/3).

**Comment by k4bek4be** [comment]
Done in f93823bb412cfb7cc62c722095c9b71ce4d91446
