### ISSUE TITLE
[Suggestion]: Add info-string in m_showwebirc module

### ISSUE THREAD

**Issue by westor7** [pirc-pl/unrealircd-modules#4]
Hello,

It would be nice to add `info-string` setting in Set block (as m_geoip_whois already have) to be able to change the SWHOIS message to what ever we want instead of touching the source.

Also this is useful for users that wanna use a non-english language in the display text too.

Example: 
```
showwebirc {
	info-string "is connecting via "; // remember the trailing space!
};
```

- Thanks!

**Comment by k4bek4be** [comment]
I think adding configuration support to this module would be "overkill", doubling the code length. I will however consider it if more people request the feature.
