### ISSUE TITLE
Metadata module issue

### ISSUE THREAD

**Issue by Shillos** [pirc-pl/unrealircd-modules#7]
I have installed your third/metadata on 2 of my servers that are Ubuntu 16.04 LTS and they work fine except the one with Ubuntu 18.04 LTS keeps making errors, but I think its something to do with the operating system all, of course, use the latest u5 5.0.3

Just that something happens when I add third/metadata on that one server... it shuts down and that's is after a rehash.

**Comment by k4bek4be** [comment]
Please send me the output of the `./unrealircd backtrace` command. You need `gdb` installed on your system for it to work.
As this text may contain some sensitive data, use a private channel for sending.

**Comment by k4bek4be** [comment]
The discussion on IRC points to the likely issue, that was compiling the updated git tree without running "make clean". Apparently it crashed before it even attempted to load the metadata module.
Feel free to report any other issues - though I hope there will be none :)

**Comment by Shillos** [comment]
There aren't any. Thanks!
