### ISSUE TITLE
geoip-connect-notice

### ISSUE THREAD

**Issue by Madriix** [pirc-pl/unrealircd-modules#9]
Hi

> geoip-connect-notice
> This one sends geoip information to a far connect (+F) snomask.
> Do not load this module on more than one server on the network. Correctly configured geoip-base or geoip-transfer is required.

Is it possible to show an example of the NOTICE ?
In order to avoid installing the module to test, because like that I can see the example if it suits me.

Thank you

**Comment by k4bek4be** [comment]
This is the unrealircd message:
`:test1.pirc.pl NOTICE k4be :*** Client connecting: test (a@83.26.202.137) [83.26.202.137] {0}`
This is geoip-connect-notice message:
`:test3.pirc.pl NOTICE k4be :test!a@83.26.202.137 is connecting from (Europe/PL) Poland`

**Comment by Madriix** [comment]
does the mesage:
: test3.pirc.pl NOTICE k4be: test! a@83.26.202.137 is connecting from (Europe / PL) Poland
is placed below:
  : test1.pirc.pl NOTICE k4be: *** Client connecting: test (a@83.26.202.137) [83.26.202.137] {0}

or the notice (unrealircd) à is replaced by geoip-connect-notice?

**Comment by k4bek4be** [comment]
The original notice is sent first.

**Comment by k4bek4be** [comment]
As of 5.0.9, it is now possible to add information to the original connect notice. But for this to work, every server would need to have a local geoip database to handle that, as the data i use is not available yet from a remote server at that point. We'd need to decide if we want to load geoip-base on every server (which i don't recommend) to use that feature. Please comment.

**Comment by westor7** [comment]
> 
> 
> As of 5.0.9, it is now possible to add information to the original connect notice. But for this to work, every server would need to have a local geoip database to handle that, as the data i use is not available yet from a remote server at that point. We'd need to decide if we want to load geoip-base on every server (which i don't recommend) to use that feature. Please comment.

I personally prefer 1 database per 1 server , yeah the negative is the memory that is gonna use for this, but it will make things less complicate.

**Comment by k4bek4be** [comment]
It's no longer relevant since u6.
